# Generated by Django 5.0.6 on 2024-05-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
    ]
