# Generated by Django 5.0.6 on 2024-05-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catebooks', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
