# Generated by Django 5.0.6 on 2024-05-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
