# Generated by Django 5.0.6 on 2024-05-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_alter_borrowedbook_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowedbook",
            name="duration",
            field=models.IntegerField(default=21),
        ),
        migrations.AlterField(
            model_name="borrowedbook",
            name="borrowed_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
