# Generated by Django 5.0.6 on 2024-05-25 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0003_borrowedbook_duration_alter_borrowedbook_borrowed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowedbook",
            name="borrowed_at",
        ),
        migrations.RemoveField(
            model_name="borrowedbook",
            name="duration",
        ),
        migrations.AddField(
            model_name="borrowedbook",
            name="borrowing_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
